#!/usr/bin/env python
"""
Regenerate requirements.txt from the live environment — the single source of
truth for the artifact's install manifest, so it never drifts from what is
actually installed.

Run after ANY dependency change:
    python scripts/gen_requirements.py            # rewrite requirements.txt (both trees)
    python scripts/gen_requirements.py --check    # exit 1 if the file has drifted (CI/prereq)

Why a script and not a hand-edited file: a fresh clone / artifact evaluator
reproduces the env from requirements.txt. A stale file = a broken reproduction
(tinyBenchmarks was once missing -> tinyMMLU crashed on baseline eval). The
regeneration logic below (exclusions, header notes, git-installed packages) is
codified once here instead of being retyped each time.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from datetime import date
from pathlib import Path

# Packages installed from a VCS/GitHub URL: `pip freeze` shows a bare
# "name==version" that will NOT resolve on PyPI, so emit the install URL instead.
GIT_PACKAGES = {
    "tinyBenchmarks": "git+https://github.com/felipemaiapolo/tinyBenchmarks",
}

# Packages present in the env but deliberately NOT shipped, with the reason.
EXCLUDE = {
    "sglang": (
        "unused by this pipeline; its flashinfer_cubin==0.6.1 pin conflicts "
        "with the required flashinfer-cubin==0.5.2 (must equal "
        "flashinfer-python==0.5.2, or every vLLM engine boot fails)"
    ),
}

# Both checkouts that must carry an identical requirements.txt.
TARGETS = [
    # Both sibling trees (merge_tools + artifacts_worktree) kept in sync; resolve
    # relative to this script so there is no machine-specific path.
    *[p / "requirements.txt" for p in
      (Path(__file__).resolve().parents[2].glob("*")) if (p / "scripts" / "gen_requirements.py").exists()],
]


def _freeze() -> list[str]:
    """`pip list --format=freeze` -> sorted 'name==version' lines (avoids the
    `@ file://` junk plain `pip freeze` emits in conda envs)."""
    out = subprocess.check_output(
        [sys.executable, "-m", "pip", "list", "--format=freeze"], text=True
    )
    return sorted(
        (ln.strip() for ln in out.splitlines() if "==" in ln and not ln.startswith("#")),
        key=str.lower,
    )


def _render() -> str:
    lines = _freeze()
    body = []
    git_notes = []
    for ln in lines:
        name = ln.split("==", 1)[0]
        low = name.lower()
        if low in {k.lower() for k in EXCLUDE}:
            continue
        if low in {k.lower() for k in GIT_PACKAGES}:
            url = next(v for k, v in GIT_PACKAGES.items() if k.lower() == low)
            git_notes.append(f"#  - {ln} is a GitHub package: pip install {url}\n"
                             f"#    (the '{ln}' line below will not resolve on PyPI; use the git URL).")
        body.append(ln)

    py = ".".join(map(str, sys.version_info[:3]))
    header = [
        "# merge_tools operational environment (conda env: mergeenv)",
        f"# Python {py} · regenerated by scripts/gen_requirements.py on {date.today().isoformat()}",
        "# EXCLUSIONS/NOTES:",
    ]
    for name, reason in EXCLUDE.items():
        ver = next((l for l in lines if l.lower().startswith(name.lower() + "==")), name)
        header.append(f"#  - {ver} present in the env but EXCLUDED: {reason}.")
    header += git_notes
    return "\n".join(header) + "\n" + "\n".join(body) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="Do not write; exit 1 if any target has drifted from the env.")
    args = ap.parse_args()

    content = _render()

    if args.check:
        drift = False
        want_pkgs = {l.split("==")[0].lower() for l in content.splitlines()
                     if "==" in l and not l.startswith("#")}
        for t in TARGETS:
            if not t.exists():
                print(f"[requirements] MISSING: {t}"); drift = True; continue
            have = {l.split("==")[0].lower() for l in t.read_text().splitlines()
                    if "==" in l and not l.startswith("#")}
            if have != want_pkgs:
                print(f"[requirements] DRIFT in {t}: "
                      f"+{sorted(want_pkgs - have)} -{sorted(have - want_pkgs)}")
                drift = True
        if drift:
            print("[requirements] run `python scripts/gen_requirements.py` to update.")
            return 1
        print("[requirements] up to date.")
        return 0

    for t in TARGETS:
        if t.parent.exists():
            t.write_text(content)
            print(f"[requirements] wrote {t}")
        else:
            print(f"[requirements] skip (no tree): {t}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
